-- ============================================================================
-- 2026_07_15_001_ub4-placeholder-inventory.sql
-- Date: 2026-07-15
-- Purpose: U-B.4 backfill unblock — resolve all 50 'ambiguous-serial'
--   quarantines (owner decision 2026-07-15: synthesize placeholder inventory).
--   For every legacy serial-less config JSON entry:
--     1. create a PLACEHOLDER inventory row (serial 'MIG-<config8>-<TYPE>-<n>',
--        Status=2 in_use, status_v2='installed', ServerUUID=config) when no
--        linked physical row exists — replace serials with real ones later;
--     2. stamp serial_number into the JSON entry (same shape as modern
--        server-add-component writes), claiming existing linked rows' serials
--        first (ID order) before inventing placeholders.
-- Affected tables: raminventory, storageinventory, caddyinventory,
--   pciecardinventory, server_configurations (JSON columns only).
-- Related feature: migration U-B.4 (07-component-migration), triage doc
--   UB4-QUARANTINE-TRIAGE-20260715.md.
-- Idempotent: INSERT IGNORE (SerialNumber UNIQUE); UPDATEs are guarded on the
--   exact pre-change column value (no-op if the config changed since the
--   2026-07-15 dump — dual-write self-materializes such configs anyway).
-- Generated by scripts/backfill/_placeholder_seeder_gen.php (scratch tree)
--   against ims_prod_replica (dump of 2026-07-15 09:51 server time).
-- ============================================================================

-- Generated 2026-07-15T12:25:06+02:00 from ims_prod_replica by _placeholder_seeder_gen.php
-- Summary:
-- Generated 2026-07-15T12:28:29+02:00 from ims_prod_replica by _placeholder_seeder_gen.php
-- Summary:
--   019eca1d ram: 8 entries stamped (0 existing rows claimed, 8 placeholders)
--   019eca1d storage: 2 entries stamped (0 existing rows claimed, 2 placeholders)
--   06ea5abb ram: 2 entries stamped (0 existing rows claimed, 2 placeholders)
--   06ea5abb storage: 2 entries stamped (0 existing rows claimed, 2 placeholders)
--   06ea5abb storage: 1 entries stamped (0 existing rows claimed, 1 placeholders)
--   06ea5abb caddy: 1 entries stamped (0 existing rows claimed, 1 placeholders)
--   809d10c9 ram: 10 entries stamped (0 existing rows claimed, 10 placeholders)
--   809d10c9 storage: 4 entries stamped (0 existing rows claimed, 4 placeholders)
--   809d10c9 storage: 1 entries stamped (0 existing rows claimed, 1 placeholders)
--   809d10c9 pciecard: 4 entries stamped (4 existing rows claimed, 0 placeholders)
--   9dbc63fa ram: 2 entries stamped (0 existing rows claimed, 2 placeholders)
--   9dbc63fa ram: 6 entries stamped (2 existing rows claimed, 4 placeholders)
--   9dbc63fa caddy: 2 entries stamped (2 existing rows claimed, 0 placeholders)
--   9dbc63fa pciecard: 1 entries stamped (0 existing rows claimed, 1 placeholders)
--   b01a5f51 ram: 4 entries stamped (2 existing rows claimed, 2 placeholders)

-- === 1. Placeholder inventory rows (INSERT IGNORE: SerialNumber is UNIQUE) ===

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-1', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-2', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-3', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-4', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-5', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-6', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-7', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-019eca1d-RAM-8', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-019eca1d-STORAGE-1', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-019eca1d-STORAGE-2', 2, 'installed', '019eca1d-069b-4ebe-91ba-6f856b1c99ef', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-06ea5abb-RAM-1', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-06ea5abb-RAM-2', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('a82df310-cb82-4f9e-bd48-2f1d171cf9a9', 'MIG-06ea5abb-STORAGE-1', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('a82df310-cb82-4f9e-bd48-2f1d171cf9a9', 'MIG-06ea5abb-STORAGE-2', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-06ea5abb-STORAGE-3', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `caddyinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('4a8a2c05-e993-4b00-acae-9f036617091c', 'MIG-06ea5abb-CADDY-1', 2, 'installed', '06ea5abb-ddb0-4945-ba88-7eba61ba3905', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-1', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-2', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-3', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-4', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-5', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-6', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-7', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-8', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-9', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-809d10c9-RAM-10', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-809d10c9-STORAGE-1', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-809d10c9-STORAGE-2', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-809d10c9-STORAGE-3', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('f54497fd-5cd3-4b5a-8cd2-276a68af11ac', 'MIG-809d10c9-STORAGE-4', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `storageinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('a82df310-cb82-4f9e-bd48-2f1d171cf9a9', 'MIG-809d10c9-STORAGE-5', 2, 'installed', '809d10c9-cff2-4e49-88a5-83dccab09f8f', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('a63d57cf-f70a-4d5c-95e6-db7173d63bd6', 'MIG-9dbc63fa-RAM-1', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('a63d57cf-f70a-4d5c-95e6-db7173d63bd6', 'MIG-9dbc63fa-RAM-2', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-9dbc63fa-RAM-3', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-9dbc63fa-RAM-4', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-9dbc63fa-RAM-5', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-9dbc63fa-RAM-6', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `pciecardinventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('07dc91dd-e630-4f4a-befb-272906748f36', 'MIG-9dbc63fa-PCIECARD-1', 2, 'installed', '9dbc63fa-900c-4c4d-bd28-7bde703b34ad', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-b01a5f51-RAM-1', 2, 'installed', 'b01a5f51-1e3c-4ea2-8473-69bbc69daa98', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

INSERT IGNORE INTO `raminventory` (`UUID`, `SerialNumber`, `Status`, `status_v2`, `ServerUUID`, `Location`, `Flag`, `Notes`, `CreatedAt`, `UpdatedAt`)
  VALUES ('9e1a4532-b693-4a59-b832-d8690bdb62fa', 'MIG-b01a5f51-RAM-2', 2, 'installed', 'b01a5f51-1e3c-4ea2-8473-69bbc69daa98', 'Noida', 'Production', 'PLACEHOLDER row created by 2026_07_15_001 migration seeder (U-B.4): physical unit exists per config JSON but was never serialized in inventory. Replace SerialNumber with the real one when known.', NOW(), NOW());

-- === 2. Stamp serial_number into config JSON entries (guarded: no-op if the column changed since the 2026-07-15 dump) ===

UPDATE `server_configurations` SET `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 14:06:29\",\"serial_number\":\"MIG-019eca1d-RAM-1\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:55:03\",\"serial_number\":\"MIG-019eca1d-RAM-2\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:56:20\",\"serial_number\":\"MIG-019eca1d-RAM-3\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:57:43\",\"serial_number\":\"MIG-019eca1d-RAM-4\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:59:51\",\"serial_number\":\"MIG-019eca1d-RAM-5\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:01:50\",\"serial_number\":\"MIG-019eca1d-RAM-6\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:06:27\",\"serial_number\":\"MIG-019eca1d-RAM-7\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:10:38\",\"serial_number\":\"MIG-019eca1d-RAM-8\"}]'
  WHERE `config_uuid` = '019eca1d-069b-4ebe-91ba-6f856b1c99ef' AND `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 14:06:29\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:55:03\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:56:20\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:57:43\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:59:51\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:01:50\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:06:27\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 13:10:38\"}]';

UPDATE `server_configurations` SET `storage_configuration` = '[{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 14:09:53\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-019eca1d-STORAGE-1\"},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 14:10:55\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-019eca1d-STORAGE-2\"}]'
  WHERE `config_uuid` = '019eca1d-069b-4ebe-91ba-6f856b1c99ef' AND `storage_configuration` = '[{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 14:09:53\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 14:10:55\",\"connection\":{\"type\":\"not_connected\"}}]';

UPDATE `server_configurations` SET `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-08 09:59:43\",\"serial_number\":\"MIG-06ea5abb-RAM-1\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:41:09\",\"serial_number\":\"MIG-06ea5abb-RAM-2\"}]'
  WHERE `config_uuid` = '06ea5abb-ddb0-4945-ba88-7eba61ba3905' AND `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-08 09:59:43\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-20 12:41:09\"}]';

UPDATE `server_configurations` SET `storage_configuration` = '[{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 06:03:45\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-06ea5abb-STORAGE-1\"},{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 06:33:29\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-06ea5abb-STORAGE-2\"},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 09:46:19\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-06ea5abb-STORAGE-3\"}]'
  WHERE `config_uuid` = '06ea5abb-ddb0-4945-ba88-7eba61ba3905' AND `storage_configuration` = '[{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 06:03:45\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 06:33:29\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 09:46:19\",\"connection\":{\"type\":\"not_connected\"}}]';

UPDATE `server_configurations` SET `caddy_configuration` = '[{\"uuid\":\"4a8a2c05-e993-4b00-acae-9f036617091c\",\"quantity\":1,\"added_at\":\"2026-04-08 11:49:13\",\"serial_number\":\"MIG-06ea5abb-CADDY-1\"}]'
  WHERE `config_uuid` = '06ea5abb-ddb0-4945-ba88-7eba61ba3905' AND `caddy_configuration` = '[{\"uuid\":\"4a8a2c05-e993-4b00-acae-9f036617091c\",\"quantity\":1,\"added_at\":\"2026-04-08 11:49:13\"}]';

UPDATE `server_configurations` SET `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 10:09:05\",\"serial_number\":\"MIG-809d10c9-RAM-1\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:43:11\",\"serial_number\":\"MIG-809d10c9-RAM-2\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:04\",\"serial_number\":\"MIG-809d10c9-RAM-3\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:16\",\"serial_number\":\"MIG-809d10c9-RAM-4\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:25\",\"serial_number\":\"MIG-809d10c9-RAM-5\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:34\",\"serial_number\":\"MIG-809d10c9-RAM-6\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:42\",\"serial_number\":\"MIG-809d10c9-RAM-7\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:53\",\"serial_number\":\"MIG-809d10c9-RAM-8\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:45:03\",\"serial_number\":\"MIG-809d10c9-RAM-9\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:49:15\",\"serial_number\":\"MIG-809d10c9-RAM-10\"}]'
  WHERE `config_uuid` = '809d10c9-cff2-4e49-88a5-83dccab09f8f' AND `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 10:09:05\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:43:11\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:04\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:16\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:25\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:34\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:42\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:44:53\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:45:03\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-16 11:49:15\"}]';

UPDATE `server_configurations` SET `storage_configuration` = '[{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:39\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-809d10c9-STORAGE-1\"},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:47\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-809d10c9-STORAGE-2\"},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:57\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-809d10c9-STORAGE-3\"},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:15:10\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-809d10c9-STORAGE-4\"},{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 11:18:07\",\"connection\":{\"type\":\"not_connected\"},\"serial_number\":\"MIG-809d10c9-STORAGE-5\"}]'
  WHERE `config_uuid` = '809d10c9-cff2-4e49-88a5-83dccab09f8f' AND `storage_configuration` = '[{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:39\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:47\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:14:57\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"f54497fd-5cd3-4b5a-8cd2-276a68af11ac\",\"quantity\":1,\"added_at\":\"2026-04-16 11:15:10\",\"connection\":{\"type\":\"not_connected\"}},{\"uuid\":\"a82df310-cb82-4f9e-bd48-2f1d171cf9a9\",\"quantity\":1,\"added_at\":\"2026-04-16 11:18:07\",\"connection\":{\"type\":\"not_connected\"}}]';

UPDATE `server_configurations` SET `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:38\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W2\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:47\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W223\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:57\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W2123\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:49:04\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W\"}]'
  WHERE `config_uuid` = '809d10c9-cff2-4e49-88a5-83dccab09f8f' AND `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:38\",\"slot_position\":\"\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:47\",\"slot_position\":\"\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:57\",\"slot_position\":\"\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:49:04\",\"slot_position\":\"\"}]';

UPDATE `server_configurations` SET `ram_configuration` = '[{\"uuid\":\"a63d57cf-f70a-4d5c-95e6-db7173d63bd6\",\"quantity\":1,\"added_at\":\"2026-04-20 13:34:02\",\"serial_number\":\"MIG-9dbc63fa-RAM-1\"},{\"uuid\":\"a63d57cf-f70a-4d5c-95e6-db7173d63bd6\",\"quantity\":1,\"added_at\":\"2026-04-20 13:36:22\",\"serial_number\":\"MIG-9dbc63fa-RAM-2\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:35:42\",\"serial_number\":\"6\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:39:06\",\"serial_number\":\"8\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:40:54\",\"serial_number\":\"MIG-9dbc63fa-RAM-3\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:42:32\",\"serial_number\":\"MIG-9dbc63fa-RAM-4\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:44:15\",\"serial_number\":\"MIG-9dbc63fa-RAM-5\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:45:34\",\"serial_number\":\"MIG-9dbc63fa-RAM-6\"}]'
  WHERE `config_uuid` = '9dbc63fa-900c-4c4d-bd28-7bde703b34ad' AND `ram_configuration` = '[{\"uuid\":\"a63d57cf-f70a-4d5c-95e6-db7173d63bd6\",\"quantity\":1,\"added_at\":\"2026-04-20 13:34:02\"},{\"uuid\":\"a63d57cf-f70a-4d5c-95e6-db7173d63bd6\",\"quantity\":1,\"added_at\":\"2026-04-20 13:36:22\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:35:42\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:39:06\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:40:54\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:42:32\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:44:15\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 06:45:34\"}]';

UPDATE `server_configurations` SET `caddy_configuration` = '[{\"uuid\":\"bf3192bf-810e-47ea-81c6-946533aad2ca\",\"quantity\":1,\"added_at\":\"2026-04-21 07:15:34\",\"serial_number\":\"QCTB4A9FCFAC84E\"},{\"uuid\":\"bf3192bf-810e-47ea-81c6-946533aad2ca\",\"quantity\":1,\"added_at\":\"2026-04-21 07:16:54\",\"serial_number\":\"2\"}]'
  WHERE `config_uuid` = '9dbc63fa-900c-4c4d-bd28-7bde703b34ad' AND `caddy_configuration` = '[{\"uuid\":\"bf3192bf-810e-47ea-81c6-946533aad2ca\",\"quantity\":1,\"added_at\":\"2026-04-21 07:15:34\"},{\"uuid\":\"bf3192bf-810e-47ea-81c6-946533aad2ca\",\"quantity\":1,\"added_at\":\"2026-04-21 07:16:54\"}]';

UPDATE `server_configurations` SET `pciecard_configurations` = '[{\"uuid\":\"07dc91dd-e630-4f4a-befb-272906748f36\",\"quantity\":1,\"added_at\":\"2026-04-21 07:18:49\",\"slot_position\":\"\",\"serial_number\":\"MIG-9dbc63fa-PCIECARD-1\"}]'
  WHERE `config_uuid` = '9dbc63fa-900c-4c4d-bd28-7bde703b34ad' AND `pciecard_configurations` = '[{\"uuid\":\"07dc91dd-e630-4f4a-befb-272906748f36\",\"quantity\":1,\"added_at\":\"2026-04-21 07:18:49\",\"slot_position\":\"\"}]';

UPDATE `server_configurations` SET `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:47:48\",\"serial_number\":\"2\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:53:57\",\"serial_number\":\"5\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:57:03\",\"serial_number\":\"MIG-b01a5f51-RAM-1\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:58:34\",\"serial_number\":\"MIG-b01a5f51-RAM-2\"}]'
  WHERE `config_uuid` = 'b01a5f51-1e3c-4ea2-8473-69bbc69daa98' AND `ram_configuration` = '[{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:47:48\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:53:57\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:57:03\"},{\"uuid\":\"9e1a4532-b693-4a59-b832-d8690bdb62fa\",\"quantity\":1,\"added_at\":\"2026-04-21 08:58:34\"}]';

-- === 3. NIC embedded-spec repair (06ea5abb): the config JSON's embedded specifications
-- snapshot for NIC f85c377e (I350-T2) is missing 'interface' — legacy computeLanesUsed()
-- reads the embedded snapshot first and counted 0 lanes while the catalog (ims-data,
-- 'PCIe 2.1 x4') counts 4, a permanent ledger check-4 mismatch. Copies the interface
-- value from ims-data into the snapshot so both models read x4. Guarded like section 2.

UPDATE `server_configurations` SET `nic_config` = '{\"nics\":[{\"uuid\":\"f85c377e-f4a2-46eb-9f2e-a466581d1ee4\",\"source_type\":\"component\",\"parent_motherboard_uuid\":null,\"onboard_index\":null,\"status\":\"in_use\",\"replaceable\":true,\"specifications\":{\"model\":\"I350-T2\",\"ports\":2,\"port_type\":\"RJ45\",\"speeds\":[\"1GbE\",\"100Mbps\",\"10Mbps\"],\"interface\":\"PCIe 2.1 x4\"},\"serial_number\":\"R180-F34-ZB-XX gigabyte\",\"slot_position\":\"pcie_x8_slot_1\"}],\"summary\":{\"total_nics\":1,\"onboard_nics\":0,\"component_nics\":1},\"last_updated\":\"2026-04-16 09:47:33\"}'
  WHERE `config_uuid` = '06ea5abb-ddb0-4945-ba88-7eba61ba3905' AND `nic_config` = '{\"nics\":[{\"uuid\":\"f85c377e-f4a2-46eb-9f2e-a466581d1ee4\",\"source_type\":\"component\",\"parent_motherboard_uuid\":null,\"onboard_index\":null,\"status\":\"in_use\",\"replaceable\":true,\"specifications\":{\"model\":\"I350-T2\",\"ports\":2,\"port_type\":\"RJ45\",\"speeds\":[\"1GbE\",\"100Mbps\",\"10Mbps\"]},\"serial_number\":\"R180-F34-ZB-XX gigabyte\",\"slot_position\":\"pcie_x8_slot_1\"}],\"summary\":{\"total_nics\":1,\"onboard_nics\":0,\"component_nics\":1},\"last_updated\":\"2026-04-16 09:47:33\"}';

-- === 4. Slot assignment for never-assigned pciecards (slot_report A-8 'slotless_card'):
-- legacy JSON carried slot_position:'' for these 6 cards. Assigns each the smallest FREE
-- PCIe slot on the config's own motherboard (legacy pcie_x{N}_slot_{n} naming, skipping
-- slots already occupied in that config's JSON). PLACEHOLDER-class data like section 1:
-- correct the physical slot later if it matters. Guarded like section 2.

UPDATE `server_configurations` SET `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:42:42\",\"slot_position\":\"pcie_x16_slot_1\"}]'
  WHERE `config_uuid` = '06ea5abb-ddb0-4945-ba88-7eba61ba3905' AND `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:42:42\",\"slot_position\":\"\"}]';

UPDATE `server_configurations` SET `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:38\",\"slot_position\":\"pcie_x4_slot_1\",\"serial_number\":\"3X8H3W2\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:47\",\"slot_position\":\"pcie_x4_slot_2\",\"serial_number\":\"3X8H3W223\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:57\",\"slot_position\":\"pcie_x8_slot_1\",\"serial_number\":\"3X8H3W2123\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:49:04\",\"slot_position\":\"pcie_x8_slot_2\",\"serial_number\":\"3X8H3W\"}]'
  WHERE `config_uuid` = '809d10c9-cff2-4e49-88a5-83dccab09f8f' AND `pciecard_configurations` = '[{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:38\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W2\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:47\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W223\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:48:57\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W2123\"},{\"uuid\":\"8f3a2c1d-5e4b-6a7c-8d9e-0f1a2b3c4d5e\",\"quantity\":1,\"added_at\":\"2026-04-20 12:49:04\",\"slot_position\":\"\",\"serial_number\":\"3X8H3W\"}]';

UPDATE `server_configurations` SET `pciecard_configurations` = '[{\"uuid\":\"07dc91dd-e630-4f4a-befb-272906748f36\",\"quantity\":1,\"added_at\":\"2026-04-21 07:18:49\",\"slot_position\":\"pcie_x16_slot_1\",\"serial_number\":\"MIG-9dbc63fa-PCIECARD-1\"}]'
  WHERE `config_uuid` = '9dbc63fa-900c-4c4d-bd28-7bde703b34ad' AND `pciecard_configurations` = '[{\"uuid\":\"07dc91dd-e630-4f4a-befb-272906748f36\",\"quantity\":1,\"added_at\":\"2026-04-21 07:18:49\",\"slot_position\":\"\",\"serial_number\":\"MIG-9dbc63fa-PCIECARD-1\"}]';

